### ISSUE TITLE
Documentation does not include Changeset APIs

### ISSUE THREAD

**Issue by ghost** [rsyncai/mergequeue-external#1]
Changeset APIs are not included in documentation [here](https://mergequeue.com/documentation). Please update the documentation to include parameters, expected behavior, and responses for:
- Creating a changeset
- Modifying a changeset
- Checking the status of a changeset
- Merging a changeset
- Triggering CI for a changeset
- Updating CI status of a changeset

**Comment by jainankit** [comment]
Added:
https://mergequeue.com/documentation#change-sets
