### ISSUE TITLE
Changeset CI status_run API does not support multiple unique names per status_run_id

### ISSUE THREAD

**Issue by ghost** [rsyncai/mergequeue-external#2]
The CI `status_run` API should support individual CI statuses per `status_run_id`, differentiated by the `name` parameter. An example use case that is not supported by the current API:

```
curl -X POST \
-H "Authorization: Bearer <API_TOKEN>" \
-H "Content-Type: application/json" \
https://mergequeue.com/api/v1/status_run \
-d '{ "status_run_id": 8, "state": "pending", "name": "full-build" }'

curl -X POST \
-H "Authorization: Bearer <API_TOKEN>" \
-H "Content-Type: application/json" \
https://mergequeue.com/api/v1/status_run \
-d '{ "status_run_id": 8, "state": "pending", "name": "secondary-build" }'

curl -X POST \
-H "Authorization: Bearer <API_TOKEN>" \
-H "Content-Type: application/json" \
https://mergequeue.com/api/v1/status_run \
-d '{ "status_run_id": 8, "state": "success", "name": "full-build" }'

curl -X POST \
-H "Authorization: Bearer <API_TOKEN>" \
-H "Content-Type: application/json" \
https://mergequeue.com/api/v1/status_run \
-d '{ "status_run_id": 8, "state": "failure", "name": "secondary-build" }'
```

**Comment by jainankit** [comment]
Hi @jgates-sq , are you suggesting that there are multiple CI builds you run with a single `status_run`. Our current API is designed assuming there's a single global CI execution for each Changeset. We still check for CI on each individual repository, but assume single global CI.

**Comment by ghost** [comment]
Hi @jainankit, yes, when our CI is initiated through the Start CI hook this triggers a number of different builds and tests that we would like to report statuses for individually on the PR/MergeQueue.

**Comment by jainankit** [comment]
Hmm, let's discuss on how that can work. Typically our system checks the status - whether it's success or failure. And based on that made decision whether the changeset can merge. In this scenario, we would not know what all status checks to validate.

**Comment by ghost** [comment]
My understanding of how this should work: for a PR to be mergable, every reported build `name` should have reported `success` for the latest `status_run_id`.

**Comment by jainankit** [comment]
@jgates-sq if we have not received any info for a build `name`, we would not know that it has to be validated.
So as soon as the `status` webhook is sent, there are no checks reported to validate. This is also the reason we have predefined checks for each repository in our single-repo queue modes.

**Comment by jainankit** [comment]
This was fixed in 04/15/2022 Release.
